# Jekyll configuration for AlexanderFerrariMiller.com

url: "https://alexanderferrarimiller.com"

include:
  - _includes

exclude:
  - README.md
  - SITE-AUDIT.md

# Almanack publication sync: 2026-09-03
