#!/usr/bin/env python3
"""Repair-once: expose the immediate descendant at a body-candidate cap."""
from pathlib import Path

TARGET = Path("tools/planet_finder_search_core.py")
text = TARGET.read_text(encoding="utf-8")

old = '''                rejection_summary = (\n                    f" capped_body={name} depth={depth}/{len(order)} "\n                    f"generated={stats.get('generated', 0):,} viable={stats.get('viable', 0):,} "\n                    f"rejects[immutable-reserved={stats.get('immutable_reserved', 0):,},"\n                    f"immutable-rim={stats.get('immutable_rim', 0):,},"\n                    f"placed-overlap={stats.get('overlap', 0):,},"\n                    f"existing-leader={stats.get('leader_existing', 0):,},"\n                    f"route={stats.get('route', 0):,},"\n                    f"leader-rim={stats.get('leader_rim', 0):,},"\n                    f"leader-graze={stats.get('leader_graze', 0):,}]"\n                )\n'''

new = '''                rejection_summary = (\n                    f" capped_body={name} depth={depth}/{len(order)} "\n                    f"generated={stats.get('generated', 0):,} viable={stats.get('viable', 0):,} "\n                    f"rejects[immutable-reserved={stats.get('immutable_reserved', 0):,},"\n                    f"immutable-rim={stats.get('immutable_rim', 0):,},"\n                    f"placed-overlap={stats.get('overlap', 0):,},"\n                    f"existing-leader={stats.get('leader_existing', 0):,},"\n                    f"route={stats.get('route', 0):,},"\n                    f"leader-rim={stats.get('leader_rim', 0):,},"\n                    f"leader-graze={stats.get('leader_graze', 0):,}]"\n                )\n                # Diagnostic only: when a parent body consumes its viable\n                # candidate allowance because every child subtree fails, show\n                # the immediate descendant's aggregate behavior.  This makes\n                # the actual squeaky wheel visible without changing search,\n                # candidate accounting, ordering, geometry, or budgets.\n                child_depth = depth + 1\n                if child_depth < len(order):\n                    child_name = order[child_depth][1][1]\n                    child_stats = diagnostic_stats.get((child_depth, child_name), {})\n                    rejection_summary += (\n                        f" child[{child_name} depth={child_depth}/{len(order)} "\n                        f"visits={depth_visits.get(child_depth, 0):,} "\n                        f"dead_ends={dead_end_visits.get((child_depth, child_name), 0):,} "\n                        f"generated={child_stats.get('generated', 0):,} "\n                        f"viable={child_stats.get('viable', 0):,} "\n                        f"rejects[immutable-reserved={child_stats.get('immutable_reserved', 0):,},"\n                        f"immutable-rim={child_stats.get('immutable_rim', 0):,},"\n                        f"placed-overlap={child_stats.get('overlap', 0):,},"\n                        f"existing-leader={child_stats.get('leader_existing', 0):,},"\n                        f"route={child_stats.get('route', 0):,},"\n                        f"leader-rim={child_stats.get('leader_rim', 0):,},"\n                        f"leader-graze={child_stats.get('leader_graze', 0):,}]]"\n                    )\n'''

count = text.count(old)
if count != 1:
    raise SystemExit(
        f"Refusing repair: expected capped rejection summary exactly once, found {count}"
    )
TARGET.write_text(text.replace(old, new, 1), encoding="utf-8")
print("Added immediate-descendant diagnostics to body-candidate cap summary.")
