#!/usr/bin/env python3
"""Create and populate observer-first Sky Notes for an inclusive ISO date range.

Every requested week is generated by the same method. The note combines:
- fixed-sky objects featured by the weekly Calendar;
- notable planetary longitude relationships from Star Almanack's preserved
  calculation-layer data; and
- a structured artwork descriptor plus a visible placeholder.

This generator never fetches an ephemeris. Approved historical model work is
reference material only and never changes runtime behavior. Production
constellation geometry is Martz/MacRobert only; Star Almanack asterisms are a
separate observer-facing layer.
"""
from __future__ import annotations

import csv
import html
import json
import math
import re
from datetime import date
from pathlib import Path

from iso_date_range import group_by_year, parse_range_args
from almanack_paths import calendar_page
from almanack_sections import type_page
from star_almanack_planets import PLANET_COLUMNS, load_weekly_longitudes

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT
PAGE_ROOTS = (ROOT / "almanack",)
BRIGHT_STARS = SOURCE_ROOT / "bright-stars-2mag.csv"
GEOMETRY_REGISTRY = ROOT / "finder-geometry" / "martz-macrobert.json"

PLANET_DISPLAY = {
    "mercury": "Mercury", "venus": "Venus", "mars": "Mars", "jupiter": "Jupiter",
    "saturn": "Saturn", "uranus": "Uranus", "neptune": "Neptune",
}
CONSTELLATION_NAMES = {
    "And": "Andromeda", "Ant": "Antlia", "Aps": "Apus", "Aqr": "Aquarius",
    "Aql": "Aquila", "Ara": "Ara", "Ari": "Aries", "Aur": "Auriga",
    "Boo": "Boötes", "Cae": "Caelum", "Cam": "Camelopardalis", "Cnc": "Cancer",
    "CVn": "Canes Venatici", "CMa": "Canis Major", "CMi": "Canis Minor",
    "Cap": "Capricornus", "Car": "Carina", "Cas": "Cassiopeia", "Cen": "Centaurus",
    "Cep": "Cepheus", "Cet": "Cetus", "Cha": "Chamaeleon", "Cir": "Circinus",
    "Col": "Columba", "Com": "Coma Berenices", "CrA": "Corona Australis",
    "CrB": "Corona Borealis", "Crv": "Corvus", "Crt": "Crater", "Cru": "Crux",
    "Cyg": "Cygnus", "Del": "Delphinus", "Dor": "Dorado", "Dra": "Draco",
    "Equ": "Equuleus", "Eri": "Eridanus", "For": "Fornax", "Gem": "Gemini",
    "Gru": "Grus", "Her": "Hercules", "Hor": "Horologium", "Hya": "Hydra",
    "Hyi": "Hydrus", "Ind": "Indus", "Lac": "Lacerta", "Leo": "Leo",
    "LMi": "Leo Minor", "Lep": "Lepus", "Lib": "Libra", "Lup": "Lupus",
    "Lyn": "Lynx", "Lyr": "Lyra", "Men": "Mensa", "Mic": "Microscopium",
    "Mon": "Monoceros", "Mus": "Musca", "Nor": "Norma", "Oct": "Octans",
    "Oph": "Ophiuchus", "Ori": "Orion", "Pav": "Pavo", "Peg": "Pegasus",
    "Per": "Perseus", "Phe": "Phoenix", "Pic": "Pictor", "Psc": "Pisces",
    "PsA": "Piscis Austrinus", "Pup": "Puppis", "Pyx": "Pyxis", "Ret": "Reticulum",
    "Sge": "Sagitta", "Sgr": "Sagittarius", "Sco": "Scorpius", "Scl": "Sculptor",
    "Sct": "Scutum", "Ser": "Serpens", "Sex": "Sextans", "Tau": "Taurus",
    "Tel": "Telescopium", "Tri": "Triangulum", "TrA": "Triangulum Australe",
    "Tuc": "Tucana", "UMa": "Ursa Major", "UMi": "Ursa Minor", "Vel": "Vela",
    "Vir": "Virgo", "Vol": "Volans", "Vul": "Vulpecula",
}
ASTERISMS = {
    "Ori": {"name": "Orion’s Belt", "members": ("Mintaka", "Alnilam", "Alnitak")},
    "Peg": {"name": "Great Square of Pegasus", "members": ("Markab", "Scheat", "Algenib", "Alpheratz")},
    "UMa": {"name": "Big Dipper", "members": ("Dubhe", "Merak", "Phecda", "Megrez", "Alioth", "Mizar", "Alkaid")},
    "Cyg": {"name": "Northern Cross", "members": ("Deneb", "Sadr", "Gienah", "Albireo")},
    "Sgr": {"name": "Teapot", "members": ("Kaus Australis", "Kaus Media", "Kaus Borealis", "Nunki", "Ascella")},
    "Leo": {"name": "Sickle", "members": ("Regulus", "Algieba", "Adhafera")},
    "Aqr": {"name": "Water Jar", "members": ("Sadalmelik", "Sadalsuud", "Sadachbia", "Skat")},
}


def canonical_asterism(asterism: dict) -> dict:
    """Resolve an observer-facing asterism to its canonical geometry-registry identity."""
    if not GEOMETRY_REGISTRY.exists():
        raise RuntimeError(f"Accepted geometry registry is missing: {GEOMETRY_REGISTRY.relative_to(ROOT)}")
    registry = json.loads(GEOMETRY_REGISTRY.read_text(encoding="utf-8"))
    wanted = str(asterism.get("name") or "").strip().casefold()
    matches = [
        (asterism_id, record)
        for asterism_id, record in (registry.get("asterisms") or {}).items()
        if str(record.get("name") or "").strip().casefold() == wanted
    ]
    if len(matches) != 1:
        raise RuntimeError(
            f"Asterism {asterism.get('name')!r} resolves to {len(matches)} canonical geometry records; expected exactly one"
        )
    asterism_id, record = matches[0]
    if record.get("geometry_status") != "accepted-paths" or not record.get("paths"):
        raise RuntimeError(f"Canonical asterism {asterism_id!r} has no accepted drawable paths")
    members = [
        member.get("display_name") or member.get("member")
        for member in (record.get("members") or [])
        if member.get("display_name") or member.get("member")
    ]
    return {"id": asterism_id, "name": record.get("name") or asterism["name"], "members": members}


def plain_text(fragment: str) -> str:
    text = re.sub(r"<br\s*/?>", " · ", fragment, flags=re.I)
    text = re.sub(r"<[^>]+>", "", text)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def calendar_events_from_page(path: Path) -> list[tuple[date, list[str]]]:
    text = path.read_text(encoding="utf-8")
    result: list[tuple[date, list[str]]] = []
    for row in re.finditer(r'<tr[^>]*data-date="(\d{4}-\d{2}-\d{2})"[^>]*>(.*?)</tr>', text, flags=re.S):
        cells = re.findall(r"<td[^>]*>(.*?)</td>", row.group(2), flags=re.S)
        if not cells:
            continue
        entries = []
        event_parts = re.findall(
            r'<(?:div|span)[^>]*class="[^"]*event-cell[^"]*"[^>]*>(.*?)</(?:div|span)>',
            cells[-1],
            flags=re.S | re.I,
        )
        if event_parts:
            parts = event_parts
        else:
            parts = re.split(r"<br\s*/?>", cells[-1], flags=re.I)
        for part in parts:
            cleaned = plain_text(part)
            if cleaned and cleaned != "—":
                entries.append(cleaned)
        result.append((date.fromisoformat(row.group(1)), entries))
    if not result:
        raise RuntimeError(f"Could not read machine-readable Calendar rows from {path.relative_to(ROOT)}")
    return result


def equatorial_to_ecliptic(ra_deg: float, dec_deg: float) -> tuple[float, float]:
    """J2000-style rotation adequate for selecting broad weekly relationships."""
    ra = math.radians(ra_deg)
    dec = math.radians(dec_deg)
    eps = math.radians(23.4392911)
    x = math.cos(dec) * math.cos(ra)
    y = math.cos(dec) * math.sin(ra) * math.cos(eps) + math.sin(dec) * math.sin(eps)
    z = -math.cos(dec) * math.sin(ra) * math.sin(eps) + math.sin(dec) * math.cos(eps)
    return math.degrees(math.atan2(y, x)) % 360.0, math.degrees(math.asin(z))


def load_bright_stars() -> list[dict]:
    with BRIGHT_STARS.open(encoding="utf-8", newline="") as handle:
        stars = []
        for row in csv.DictReader(handle):
            if not row.get("proper"):
                continue
            ra_deg = float(row["ra_h"]) * 15.0
            dec_deg = float(row["dec_deg"])
            lon_deg, lat_deg = equatorial_to_ecliptic(ra_deg, dec_deg)
            stars.append({
                "name": row["proper"], "bayer": row["bayer"], "con": row["con"],
                "ra_deg": ra_deg, "dec_deg": dec_deg,
                "ecliptic_lon_deg": lon_deg, "ecliptic_lat_deg": lat_deg,
                "mag": float(row["representative_vmax"].split(";")[0]),
            })
    return stars


def longitude_distance(a: float, b: float) -> float:
    return abs((a - b + 180.0) % 360.0 - 180.0)


def notable_planet_relations(week: int, yearly: dict[int, dict[str, float]], stars: list[dict]) -> list[dict]:
    """Select relationships justified by the preserved longitude data."""
    if week not in yearly:
        raise RuntimeError(f"Missing preserved planetary row for ISO week {week:02d}")
    positions = yearly[week]
    candidates: list[dict] = []
    ecliptic_stars = [star for star in stars if abs(star["ecliptic_lat_deg"]) <= 6.0]
    for planet in PLANET_COLUMNS:
        plon = positions[planet]
        for star in ecliptic_stars:
            delta = longitude_distance(plon, star["ecliptic_lon_deg"])
            if delta > 5.0:
                continue
            relation = {
                "kind": "planet-star-longitude", "planet": PLANET_DISPLAY[planet],
                "planet_longitude_deg": round(plon, 3), "star": star["name"],
                "constellation": star["con"],
                "star_ecliptic_longitude_deg": round(star["ecliptic_lon_deg"], 3),
                "star_ecliptic_latitude_deg": round(star["ecliptic_lat_deg"], 3),
                "longitude_separation_deg": round(delta, 1),
                "basis": "Star Almanack preserved geocentric tropical ecliptic longitude",
            }
            asterism = ASTERISMS.get(star["con"])
            if asterism and star["name"] in asterism["members"]:
                relation["asterism"] = asterism["name"]
            candidates.append(relation)
    planets = list(PLANET_COLUMNS)
    for i, first in enumerate(planets):
        for second in planets[i + 1:]:
            delta = longitude_distance(positions[first], positions[second])
            if delta <= 4.0:
                candidates.append({
                    "kind": "planet-planet-longitude", "planet": PLANET_DISPLAY[first],
                    "other_planet": PLANET_DISPLAY[second],
                    "planet_longitude_deg": round(positions[first], 3),
                    "other_longitude_deg": round(positions[second], 3),
                    "longitude_separation_deg": round(delta, 1),
                    "basis": "Star Almanack preserved geocentric tropical ecliptic longitude",
                })
    candidates.sort(key=lambda item: item["longitude_separation_deg"])
    return candidates[:4]


def featured_fixed_sky(entries: list[str], stars: list[dict]) -> list[dict]:
    result = []
    joined = "\n".join(entries)
    for star in stars:
        if re.search(rf"(?<![A-Za-z]){re.escape(star['name'])}(?![A-Za-z])", joined, flags=re.I):
            result.append({"type": "star", "name": star["name"], "constellation": star["con"]})
    for entry in entries:
        if re.search(r"(?<![A-Za-z0-9])M(?:110|10\d|[1-9]\d?)(?!\d)", entry):
            name = re.split(r"\s+[—-]\s+", entry, maxsplit=1)[0].strip()
            if name and all(item["name"] != name for item in result):
                result.append({"type": "deep-sky", "name": name})
    return result[:6]


def fixed_sky_context(features: list[dict]) -> tuple[str | None, dict | None]:
    for item in features:
        con = item.get("constellation")
        if con in ASTERISMS:
            return con, ASTERISMS[con]
    for item in features:
        con = item.get("constellation")
        if con:
            return con, None
    return None, None


def relation_sentence(item: dict) -> str:
    sep = item["longitude_separation_deg"]
    if item["kind"] == "planet-planet-longitude":
        return f"{item['planet']} and {item['other_planet']} are separated by about {sep:.1f}° in geocentric ecliptic longitude at the Monday 00:00 UTC snapshot."
    constellation = CONSTELLATION_NAMES.get(item["constellation"], item["constellation"])
    if item.get("asterism"):
        return f"{item['planet']} is about {sep:.1f}° in ecliptic longitude from {item['star']}, one of the stars used to orient {item['asterism']} in {constellation}."
    return f"{item['planet']} is about {sep:.1f}° in ecliptic longitude from {item['star']} in {constellation}."


def artwork_descriptor(year: int, week: int, fixed: list[dict], relations: list[dict]) -> dict | None:
    con, asterism = fixed_sky_context(fixed)
    if con is None:
        return None
    canonical = canonical_asterism(asterism) if asterism else None
    return {
        "schema_version": 1, "id": f"{year}-W{week:02d}-stellar-finder",
        "week": f"{year}-W{week:02d}", "kind": "stellar-finder",
        "geometry": {"constellation_system": "Martz/MacRobert", "constellation_abbreviation": con, "on_missing_geometry": "fail", "invent_geometry": False},
        "style": {
            "background": "night-sky",
            "constellation": {"stroke": "#5c8fe8", "role": "ordinary constellation figure"},
            "asterism": {"stroke": "#59c86d", "role": "orienting asterism"},
            "target": {"stroke": "#ffd84d", "fill": "none", "role": "open target circle"},
            "target_arrows": False,
        },
        "constellation": CONSTELLATION_NAMES.get(con, con),
        "asterism": canonical,
        "targets": [{"type": item["type"], "name": item["name"]} for item in fixed[:3]],
        "planetary_context": relations[:2],
        "planet_plot_policy": "do not plot from longitude alone; require preserved 2-D Star Almanack position data",
        "reference_standard": "docs/finder-standard.md",
    }


def generated_note(year: int, week: int, page_path: Path, yearly: dict[int, dict[str, float]], stars: list[dict]) -> dict:
    rows = calendar_events_from_page(page_path)
    monday, sunday = rows[0][0], rows[-1][0]
    entries = [entry for _, items in rows for entry in items]
    fixed = featured_fixed_sky(entries, stars)
    relations = notable_planet_relations(week, yearly, stars)
    moon = next((entry for entry in entries if re.search(r"\b(New Moon|First Quarter|Full Moon|Last Quarter)\b", entry, flags=re.I)), None)
    opening = f"ISO {year}-W{week:02d} runs from {monday.strftime('%B')} {monday.day} through {sunday.strftime('%B')} {sunday.day}."
    if relations:
        opening += " " + " ".join(relation_sentence(item) for item in relations[:2])
    moon_text = moon or "No principal lunar phase is listed this week"
    if moon and "New Moon" in moon:
        condition = "The dark Moon favors faint targets and extended star fields."
    elif moon and "Full Moon" in moon:
        condition = "Bright moonlight favors prominent stars and planets while reducing contrast on faint deep-sky objects."
    elif moon:
        condition = "Moderate moonlight makes timing and local sky position important for faint targets."
    else:
        condition = "Check the Moon's position each night and favor darker hours for low-contrast targets."
    star_names = [item["name"] for item in fixed if item["type"] == "star"]
    deep_names = [item["name"] for item in fixed if item["type"] == "deep-sky"]
    naked_targets = ", ".join(star_names[:3]) if star_names else "the brightest seasonal stars and the zodiac"
    binocular_targets = ", ".join((deep_names + star_names)[:3]) if (deep_names or star_names) else "the week’s richest fixed-star fields"
    telescope_targets = ", ".join(deep_names[:2]) if deep_names else "the compact fixed-sky targets selected for the week"
    planet_paragraph = " ".join(relation_sentence(item) for item in relations) if relations else "No close longitude relationship passes the conservative weekly selection threshold; use the Planet Finder for the broader Solar-System pattern."
    note = "\n\n".join((
        opening,
        f"**Naked eye:** {moon_text}. {condition} Use {naked_targets} as the week’s fixed-sky framework.",
        f"**Planets:** {planet_paragraph}",
        f"**Binoculars:** Favor {binocular_targets}; wide fields help connect the charted geometry to the real sky.",
        f"**Small telescope:** Concentrate on {telescope_targets}. Increase magnification only after the target and surrounding pattern are secure.",
    ))
    return {
        "week": f"W{week:02d}", "title": f"Observer’s guide for ISO {year}-W{week:02d}", "status": "generated",
        "planetary_source": f"weekly-ephemeris-{year}.csv",
        "planetary_coordinate": "geocentric tropical ecliptic longitude; Monday 00:00 UTC",
        "fixed_sky": fixed, "planet_relations": relations,
        "note": note,
    }


def write_generated_source(year: int, week: int, payload: dict) -> Path:
    directory = SOURCE_ROOT / "generated-sky-notes" / str(year)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"W{week:02d}.json"
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path


def inline_markup(text: str) -> str:
    escaped = html.escape(text, quote=False)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", escaped)
    return escaped


def render_note(note: str) -> str:
    paragraphs = [part.strip() for part in re.split(r"\n\s*\n", note.strip()) if part.strip()]
    return "\n".join(f"<p>{inline_markup(' '.join(part.splitlines()))}</p>" for part in paragraphs)


def render_artwork_placeholder(descriptor: dict | None) -> str:
    if descriptor is None:
        return ""
    encoded = html.escape(json.dumps(descriptor, ensure_ascii=False, separators=(",", ":")), quote=True)
    constellation = descriptor["constellation"]
    asterism = descriptor.get("asterism")
    subject = f"{asterism['name']} in {constellation}" if asterism else constellation
    targets = [item["name"] for item in descriptor.get("targets", [])]
    target_text = ", ".join(targets) if targets else "weekly observing targets"
    caption = f"Artwork descriptor: {subject}; highlight {target_text}."
    return (
        f'<figure class="sky-note-artwork-placeholder" data-sky-note-artwork-placeholder="true" data-artwork-descriptor="{encoded}">'
        '<div class="sky-note-artwork-placeholder-box"><strong>Sky Note artwork pending</strong><br>'
        'The artwork workflow will render this descriptor only from accepted Star Almanack geometry.</div>'
        f'<figcaption>{html.escape(caption)}</figcaption></figure>'
    )


def sky_note_bounds(text: str, path: Path) -> tuple[int, int]:
    marker = "<h3>Sky Note</h3>"
    start = text.find(marker)
    if start < 0:
        raise RuntimeError(f"Missing Sky Note heading in {path.relative_to(ROOT)}")
    body_start = start + len(marker)
    match = re.search(r"<h[23]>.*?</h[23]>", text[body_start:], flags=re.S)
    end = body_start + match.start() if match else text.find("</main>", body_start)
    if end < 0:
        end = len(text)
    return body_start, end


def patch_page(path: Path, payload: dict) -> bool:
    text = path.read_text(encoding="utf-8")
    body_start, end = sky_note_bounds(text, path)
    placeholder = render_artwork_placeholder(payload["artwork"])
    new_body = "\n" + render_note(payload["note"]) + "\n"
    if placeholder:
        new_body += placeholder + "\n"
    new = text[:body_start] + new_body + text[end:]
    if new == text:
        return False
    path.write_text(new, encoding="utf-8")
    return True


def main() -> None:
    start, end, weeks = parse_range_args("Create and populate Star Almanack Sky Notes by inclusive ISO date range")
    stars = load_bright_stars()
    grouped = group_by_year(weeks)
    yearly = {year: load_weekly_longitudes(year) for year in grouped}
    changed = 0
    for item in weeks:
        week_key = f"W{item.week:02d}"
        public_page = calendar_page(item.year, item.week)
        if not public_page.exists():
            raise RuntimeError(f"Missing weekly page: {public_page.relative_to(ROOT)}")
        payload = generated_note(item.year, item.week, public_page, yearly[item.year], stars)
        source = write_generated_source(item.year, item.week, payload)
        for root in PAGE_ROOTS:
            path = type_page(root, item.year, item.week, "sky-notes")
            if not path.exists():
                raise RuntimeError(f"Missing weekly page: {path.relative_to(ROOT)}")
            if patch_page(path, payload):
                changed += 1
        art_state = "artwork descriptor emitted" if payload["artwork"] else "no stellar artwork descriptor needed"
        print(f"Generated Sky Note for ISO {item.year}-{week_key}: {source.relative_to(ROOT)} ({art_state})")
    print(f"Sky Notes complete for {start.isoformat()} through {end.isoformat()}: {len(weeks)} notes generated, {changed} page copies updated")


if __name__ == "__main__":
    main()
