#!/usr/bin/env python3
"""Create and populate observer-first Sky Notes for an inclusive ISO date range.

Every requested week is generated by the same method. The note combines:
- fixed-sky objects featured by the weekly Calendar;
- geometrically computed close planet/bright-star relationships from the JPL
  weekly ephemeris and the HYG bright-star catalog; and
- a structured artwork descriptor plus a visible placeholder.

Approved historical model work is reference material only and never changes
runtime behavior. Production constellation geometry is explicitly Martz-only;
asterisms are a separate Star Almanack layer.
"""
from __future__ import annotations

import csv
import html
import json
import math
import re
from datetime import date
from pathlib import Path

import populate_ephemeris as ephemeris
from iso_date_range import group_by_year, parse_range_args

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "Star-Almanack-Repo"
PAGE_ROOTS = (ROOT / "Star-Almanack-Repo" / "site", ROOT / "almanack")
BRIGHT_STARS = SOURCE_ROOT / "bright-stars-2mag.csv"

PLANETS = ("mercury", "venus", "mars", "jupiter", "saturn", "uranus", "neptune")
PLANET_DISPLAY = {
    "mercury": "Mercury", "venus": "Venus", "mars": "Mars", "jupiter": "Jupiter",
    "saturn": "Saturn", "uranus": "Uranus", "neptune": "Neptune",
}
CONSTELLATION_NAMES = {
    "Aqr": "Aquarius", "Aur": "Auriga", "Boo": "Boötes", "Cas": "Cassiopeia",
    "CMa": "Canis Major", "Cyg": "Cygnus", "Gem": "Gemini", "Leo": "Leo",
    "Ori": "Orion", "Peg": "Pegasus", "Sgr": "Sagittarius", "Tau": "Taurus",
    "UMa": "Ursa Major", "UMi": "Ursa Minor", "Vir": "Virgo",
}
ASTERISMS = {
    "Ori": {"name": "Orion’s Belt", "members": ("Mintaka", "Alnilam", "Alnitak")},
    "Peg": {"name": "Great Square of Pegasus", "members": ("Markab", "Scheat", "Algenib", "Alpheratz")},
    "UMa": {"name": "Big Dipper", "members": ("Dubhe", "Merak", "Phecda", "Megrez", "Alioth", "Mizar", "Alkaid")},
    "Cyg": {"name": "Northern Cross", "members": ("Deneb", "Sadr", "Gienah", "Albireo")},
    "Sgr": {"name": "Teapot", "members": ("Kaus Australis", "Kaus Media", "Kaus Borealis", "Nunki", "Ascella")},
    "Leo": {"name": "Sickle", "members": ("Regulus", "Algieba", "Adhafera")},
    "Aqr": {"name": "Water Jar", "members": ("Sadalmelik", "Sadalsuud", "Sadachbia", "Skat")},
}


def plain_text(fragment: str) -> str:
    text = re.sub(r"<br\s*/?>", " · ", fragment, flags=re.I)
    text = re.sub(r"<[^>]+>", "", text)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def calendar_events_from_page(path: Path) -> list[tuple[date, list[str]]]:
    text = path.read_text(encoding="utf-8")
    result: list[tuple[date, list[str]]] = []
    for row in re.finditer(r'<tr[^>]*data-date="(\d{4}-\d{2}-\d{2})"[^>]*>(.*?)</tr>', text, flags=re.S):
        cells = re.findall(r"<td[^>]*>(.*?)</td>", row.group(2), flags=re.S)
        if not cells:
            continue
        entries = []
        for part in re.split(r"<br\s*/?>", cells[-1], flags=re.I):
            cleaned = plain_text(part)
            if cleaned and cleaned != "—":
                entries.append(cleaned)
        result.append((date.fromisoformat(row.group(1)), entries))
    if not result:
        raise RuntimeError(f"Could not read machine-readable Calendar rows from {path.relative_to(ROOT)}")
    return result


def load_bright_stars() -> list[dict]:
    with BRIGHT_STARS.open(encoding="utf-8", newline="") as handle:
        stars = []
        for row in csv.DictReader(handle):
            if not row.get("proper"):
                continue
            stars.append({
                "name": row["proper"],
                "con": row["con"],
                "ra_deg": float(row["ra_h"]) * 15.0,
                "dec_deg": float(row["dec_deg"]),
                "mag": float(row["representative_vmax"].split(";")[0]),
            })
    return stars


def fetch_ephemeris(year: int) -> dict[str, list[tuple[float, float, float | None, float | None]]]:
    data = {}
    for _, key, command in ephemeris.TARGETS:
        if key not in PLANETS:
            continue
        print(f"Fetching {year} {key} for Sky Note geometry from JPL Horizons")
        data[key] = ephemeris.horizons_ephemeris(year, command)
    return data


def ecliptic_to_equatorial(lon_deg: float, lat_deg: float) -> tuple[float, float]:
    lon = math.radians(lon_deg)
    lat = math.radians(lat_deg)
    eps = math.radians(23.4392911)
    x = math.cos(lat) * math.cos(lon)
    y = math.cos(lat) * math.sin(lon) * math.cos(eps) - math.sin(lat) * math.sin(eps)
    z = math.cos(lat) * math.sin(lon) * math.sin(eps) + math.sin(lat) * math.cos(eps)
    return math.degrees(math.atan2(y, x)) % 360.0, math.degrees(math.asin(z))


def angular_separation(ra1: float, dec1: float, ra2: float, dec2: float) -> float:
    r1, d1, r2, d2 = map(math.radians, (ra1, dec1, ra2, dec2))
    cosine = math.sin(d1) * math.sin(d2) + math.cos(d1) * math.cos(d2) * math.cos(r1 - r2)
    return math.degrees(math.acos(max(-1.0, min(1.0, cosine))))


def notable_planet_relations(week: int, yearly, stars: list[dict]) -> list[dict]:
    candidates = []
    for planet in PLANETS:
        lon, lat, magnitude, elongation = yearly[planet][week - 1]
        if lon is None or lat is None or (elongation is not None and elongation < 20.0):
            continue
        pra, pdec = ecliptic_to_equatorial(lon, lat)
        nearest = min(stars, key=lambda star: angular_separation(pra, pdec, star["ra_deg"], star["dec_deg"]))
        sep = angular_separation(pra, pdec, nearest["ra_deg"], nearest["dec_deg"])
        if sep > 8.0:
            continue
        relation = {
            "planet": PLANET_DISPLAY[planet],
            "star": nearest["name"],
            "constellation": nearest["con"],
            "separation_deg": round(sep, 1),
            "magnitude": magnitude,
        }
        asterism = ASTERISMS.get(nearest["con"])
        if asterism and nearest["name"] in asterism["members"]:
            relation["asterism"] = asterism["name"]
        candidates.append(relation)
    candidates.sort(key=lambda item: item["separation_deg"])
    return candidates[:3]


def featured_fixed_sky(entries: list[str], stars: list[dict]) -> list[dict]:
    result = []
    joined = "\n".join(entries)
    for star in stars:
        if re.search(rf"(?<![A-Za-z]){re.escape(star['name'])}(?![A-Za-z])", joined, flags=re.I):
            result.append({"type": "star", "name": star["name"], "constellation": star["con"]})
    for entry in entries:
        if re.search(r"(?<![A-Za-z0-9])M(?:110|10\d|[1-9]\d?)(?!\d)", entry):
            name = re.split(r"\s+[—-]\s+", entry, maxsplit=1)[0].strip()
            if name and all(item["name"] != name for item in result):
                result.append({"type": "deep-sky", "name": name})
    return result[:6]


def fixed_sky_context(features: list[dict]) -> tuple[str | None, dict | None]:
    for item in features:
        con = item.get("constellation")
        if con in ASTERISMS:
            return con, ASTERISMS[con]
    for item in features:
        con = item.get("constellation")
        if con:
            return con, None
    return None, None


def relation_sentence(item: dict) -> str:
    if item.get("asterism"):
        return (
            f"{item['planet']} lies about {item['separation_deg']:.1f}° from {item['star']}, "
            f"placing it near {item['asterism']} in {CONSTELLATION_NAMES.get(item['constellation'], item['constellation'])}."
        )
    return (
        f"{item['planet']} lies about {item['separation_deg']:.1f}° from {item['star']} "
        f"in {CONSTELLATION_NAMES.get(item['constellation'], item['constellation'])}."
    )


def artwork_descriptor(year: int, week: int, fixed: list[dict], relations: list[dict]) -> dict:
    con, asterism = fixed_sky_context(fixed)
    if con is None and relations:
        con = relations[0]["constellation"]
        asterism = ASTERISMS.get(con)

    targets = [item["name"] for item in fixed[:3]]
    dynamic = [item["planet"] for item in relations[:2]]
    descriptor = {
        "schema_version": 1,
        "week": f"{year}-W{week:02d}",
        "kind": "observer-finder-placeholder",
        "geometry": {
            "constellation_source": "Martz 88-constellation accepted geometry only",
            "on_missing_geometry": "fail; never improvise",
        },
        "style": {
            "constellation_lines": "blue",
            "asterism_overlay": "green",
            "targets_and_hops": "yellow",
        },
        "constellation": CONSTELLATION_NAMES.get(con, con) if con else None,
        "constellation_abbreviation": con,
        "asterism": asterism["name"] if asterism else None,
        "fixed_targets": targets,
        "dynamic_targets": dynamic,
        "planet_relations": relations[:2],
    }
    if descriptor["asterism"]:
        descriptor["instruction"] = (
            f"Draw the accepted Martz {descriptor['constellation']} figure in blue; "
            f"overlay {descriptor['asterism']} in green; circle the featured targets in yellow; "
            "show simple observer-facing hops to any highlighted planet or deep-sky target."
        )
    elif descriptor["constellation"]:
        descriptor["instruction"] = (
            f"Draw the accepted Martz {descriptor['constellation']} figure in blue; "
            "circle the featured targets in yellow; add only computed observer-facing hops."
        )
    else:
        descriptor["instruction"] = "Show the featured targets and computed planetary relationship without inventing constellation geometry."
    return descriptor


def generated_note(year: int, week: int, page_path: Path, yearly_ephemeris, stars: list[dict]) -> dict:
    rows = calendar_events_from_page(page_path)
    monday, sunday = rows[0][0], rows[-1][0]
    entries = [entry for _, items in rows for entry in items]
    fixed = featured_fixed_sky(entries, stars)
    relations = notable_planet_relations(week, yearly_ephemeris, stars)

    moon = next((entry for entry in entries if re.search(r"\b(New Moon|First Quarter|Full Moon|Last Quarter)\b", entry, flags=re.I)), None)
    highlights = [item["name"] for item in fixed[:3]]
    opening = f"ISO {year}-W{week:02d} runs from {monday.strftime('%B')} {monday.day} through {sunday.strftime('%B')} {sunday.day}."
    if highlights:
        opening += " Fixed-sky highlights include " + ", ".join(highlights) + "."
    if relations:
        opening += " " + " ".join(relation_sentence(item) for item in relations[:2])

    moon_text = moon or "No principal lunar phase is listed this week"
    if moon and "New Moon" in moon:
        condition = "The dark Moon favors faint targets and extended star fields."
    elif moon and "Full Moon" in moon:
        condition = "Bright moonlight favors prominent stars and planets while reducing contrast on faint deep-sky objects."
    elif moon:
        condition = "Moderate moonlight makes timing and local sky position important for faint targets."
    else:
        condition = "Check the Moon's position each night and favor darker hours for low-contrast targets."

    star_names = [item["name"] for item in fixed if item["type"] == "star"]
    deep_names = [item["name"] for item in fixed if item["type"] == "deep-sky"]
    naked_targets = ", ".join(star_names[:3]) if star_names else "the brightest seasonal stars and the zodiac"
    binocular_targets = ", ".join((deep_names + star_names)[:3]) if (deep_names or star_names) else "the week’s richest fixed-star fields"
    telescope_targets = ", ".join(deep_names[:2]) if deep_names else "the compact targets selected from the weekly ephemeris"

    planet_paragraph = (
        " ".join(relation_sentence(item) for item in relations)
        if relations else
        "No planet lies within 8° of a cataloged bright star at the Monday 00:00 UTC snapshot, so use the Planet Finder for the week’s broader Solar-System geometry."
    )

    note = "\n\n".join((
        opening,
        f"**Naked eye:** {moon_text}. {condition} Use {naked_targets} as the week’s fixed-sky framework.",
        f"**Planets:** {planet_paragraph}",
        f"**Binoculars:** Favor {binocular_targets}; wide fields help connect the charted geometry to the real sky.",
        f"**Small telescope:** Concentrate on {telescope_targets}. Increase magnification only after the target and surrounding pattern are secure.",
    ))
    art = artwork_descriptor(year, week, fixed, relations)
    return {
        "week": f"W{week:02d}",
        "title": f"Observer’s guide for ISO {year}-W{week:02d}",
        "status": "generated",
        "fixed_sky": fixed,
        "planet_relations": relations,
        "artwork": art,
        "note": note,
    }


def write_generated_source(year: int, week: int, payload: dict) -> Path:
    directory = SOURCE_ROOT / "generated-sky-notes" / str(year)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"W{week:02d}.json"
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path


def inline_markup(text: str) -> str:
    escaped = html.escape(text, quote=False)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", escaped)
    return escaped


def render_note(note: str) -> str:
    paragraphs = [part.strip() for part in re.split(r"\n\s*\n", note.strip()) if part.strip()]
    return "\n".join(f"<p>{inline_markup(' '.join(part.splitlines()))}</p>" for part in paragraphs)


def render_artwork_placeholder(descriptor: dict) -> str:
    encoded = html.escape(json.dumps(descriptor, ensure_ascii=False, separators=(",", ":")), quote=True)
    constellation = descriptor.get("constellation") or "weekly sky"
    asterism = descriptor.get("asterism")
    subject = f"{asterism} in {constellation}" if asterism else constellation
    targets = descriptor.get("fixed_targets", []) + descriptor.get("dynamic_targets", [])
    target_text = ", ".join(targets) if targets else "weekly observing targets"
    caption = f"Artwork placeholder: {subject}; highlight {target_text}."
    return (
        f'<figure class="sky-note-artwork-placeholder" data-sky-note-artwork-placeholder="true" '
        f'data-artwork-descriptor="{encoded}">'
        '<div class="sky-note-artwork-placeholder-box"><strong>Sky Note artwork placeholder</strong><br>'
        f'{html.escape(descriptor["instruction"])}</div>'
        f'<figcaption>{html.escape(caption)}</figcaption></figure>'
    )


def sky_note_bounds(text: str, path: Path) -> tuple[int, int]:
    marker = "<h3>Sky Note</h3>"
    start = text.find(marker)
    if start < 0:
        raise RuntimeError(f"Missing Sky Note heading in {path.relative_to(ROOT)}")
    body_start = start + len(marker)
    match = re.search(r"<h[23]>.*?</h[23]>", text[body_start:], flags=re.S)
    end = body_start + match.start() if match else text.find("</main>", body_start)
    if end < 0:
        end = len(text)
    return body_start, end


def patch_page(path: Path, payload: dict) -> bool:
    text = path.read_text(encoding="utf-8")
    body_start, end = sky_note_bounds(text, path)
    new_body = "\n" + render_note(payload["note"]) + "\n" + render_artwork_placeholder(payload["artwork"]) + "\n"
    new = text[:body_start] + new_body + text[end:]
    if new == text:
        return False
    path.write_text(new, encoding="utf-8")
    return True


def main() -> None:
    start, end, weeks = parse_range_args("Create and populate Star Almanack Sky Notes by inclusive ISO date range")
    stars = load_bright_stars()
    grouped = group_by_year(weeks)
    yearly = {year: fetch_ephemeris(year) for year in grouped}
    changed = 0

    for item in weeks:
        week_key = f"W{item.week:02d}"
        public_page = ROOT / "almanack" / str(item.year) / week_key / "index.html"
        if not public_page.exists():
            raise RuntimeError(f"Missing weekly page: {public_page.relative_to(ROOT)}")

        payload = generated_note(item.year, item.week, public_page, yearly[item.year], stars)
        source = write_generated_source(item.year, item.week, payload)

        for root in PAGE_ROOTS:
            path = root / str(item.year) / week_key / "index.html"
            if not path.exists():
                raise RuntimeError(f"Missing weekly page: {path.relative_to(ROOT)}")
            if patch_page(path, payload):
                changed += 1
        print(f"Generated Sky Note for ISO {item.year}-{week_key}: {source.relative_to(ROOT)}")

    print(
        f"Sky Notes complete for {start.isoformat()} through {end.isoformat()}: "
        f"{len(weeks)} notes generated, {changed} page copies updated"
    )


if __name__ == "__main__":
    main()
